include $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../common/config.mk)

FPGA_CONFIG_FORMAT := 3
FPGA_NAME := u55c
FPGA_TYPE := alveo
FPGA_PART := xcu55c-fsvh2892-2L-e
FPGA_PLATFORM := xilinx_u55c_gen3x16_xdma_3_202210_1
FPGA_BOARD_PART :=
FPGA_CLOCK_MHZ := 300
FPGA_VIVADO_VERSION := 2022.2
FPGA_VITIS_VERSION := 2022.2
FPGA_VITIS_TARGET := hw
FPGA_TIMING_WNS_MIN_NS := 0.000
FPGA_VIVADO_SYNTH_JOBS := 4
FPGA_VIVADO_IMPL_JOBS := 8
FPGA_VIVADO_IMPL_STRATEGY := Performance_ExplorePostRoutePhysOpt
FPGA_VIVADO_IMPL_STRATEGY_SEARCH := 0

FPGA_DEFAULT_SOC := ysyx
FPGA_DEFAULT_XLEN := 32
FPGA_M := 1
FPGA_F := 1

FPGA_MEMORY_KIND := hbm
FPGA_FLOATING_FALLBACK := host-mailbox
FPGA_MEMORY_BASE := 0x80000000
FPGA_MEMORY_HOST_BASE := 0x00000000
FPGA_MEMORY_SIZE := 0x08000000
FPGA_CONTROL_BASE := 0xa0000000
FPGA_MAILBOX_BASE := 0xa0010000

FPGA_MUL_CYCLES := 3
FPGA_MUL_II := 1
FPGA_DIV_CYCLES := 37
FPGA_DIV_II := 1
FPGA_DIV_IP_CYCLES := 34
FPGA_DIV_ADAPTER_CYCLES := 3
FPGA_FADD_CYCLES := 3
FPGA_FADD_II := 1
FPGA_FMUL_CYCLES := 4
FPGA_FMUL_II := 1
FPGA_FDIV_CYCLES := 29
FPGA_FDIV_II := 1
FPGA_FMA_CYCLES := 4
FPGA_FMA_II := 1
FPGA_FSQRT_CYCLES := 29
FPGA_FSQRT_II := 1
FPGA_FCVT_CYCLES := 7
FPGA_FCVT_II := 1
FPGA_FCMP_CYCLES := 3
FPGA_FCMP_II := 1
