`ifndef NPC_FPGA_XLEN
`define NPC_FPGA_XLEN 32
`endif

module NpcFpgaKernel #(
  parameter [31:0] GUEST_MEMORY_BASE = 32'h8000_0000
) (
  input  wire                         ap_clk,
  input  wire                         ap_rst_n,
  output wire                         interrupt,

  output wire                         m_axi_gmem_awvalid,
  input  wire                         m_axi_gmem_awready,
  output wire [63:0]                  m_axi_gmem_awaddr,
  output wire [3:0]                   m_axi_gmem_awid,
  output wire [7:0]                   m_axi_gmem_awlen,
  output wire [2:0]                   m_axi_gmem_awsize,
  output wire [1:0]                   m_axi_gmem_awburst,
  output wire                         m_axi_gmem_awlock,
  output wire [3:0]                   m_axi_gmem_awcache,
  output wire [2:0]                   m_axi_gmem_awprot,
  output wire [3:0]                   m_axi_gmem_awqos,
  output wire                         m_axi_gmem_wvalid,
  input  wire                         m_axi_gmem_wready,
  output wire [`NPC_FPGA_XLEN-1:0]   m_axi_gmem_wdata,
  output wire [`NPC_FPGA_XLEN/8-1:0] m_axi_gmem_wstrb,
  output wire                         m_axi_gmem_wlast,
  input  wire                         m_axi_gmem_bvalid,
  output wire                         m_axi_gmem_bready,
  input  wire [3:0]                   m_axi_gmem_bid,
  input  wire [1:0]                   m_axi_gmem_bresp,
  output wire                         m_axi_gmem_arvalid,
  input  wire                         m_axi_gmem_arready,
  output wire [63:0]                  m_axi_gmem_araddr,
  output wire [3:0]                   m_axi_gmem_arid,
  output wire [7:0]                   m_axi_gmem_arlen,
  output wire [2:0]                   m_axi_gmem_arsize,
  output wire [1:0]                   m_axi_gmem_arburst,
  output wire                         m_axi_gmem_arlock,
  output wire [3:0]                   m_axi_gmem_arcache,
  output wire [2:0]                   m_axi_gmem_arprot,
  output wire [3:0]                   m_axi_gmem_arqos,
  input  wire                         m_axi_gmem_rvalid,
  output wire                         m_axi_gmem_rready,
  input  wire [3:0]                   m_axi_gmem_rid,
  input  wire [`NPC_FPGA_XLEN-1:0]   m_axi_gmem_rdata,
  input  wire [1:0]                   m_axi_gmem_rresp,
  input  wire                         m_axi_gmem_rlast,

`ifdef NPC_FPGA_RUNTIME_TRACE
  output wire                         m_axi_trace_awvalid,
  input  wire                         m_axi_trace_awready,
  output wire [63:0]                  m_axi_trace_awaddr,
  output wire [3:0]                   m_axi_trace_awid,
  output wire [7:0]                   m_axi_trace_awlen,
  output wire [2:0]                   m_axi_trace_awsize,
  output wire [1:0]                   m_axi_trace_awburst,
  output wire                         m_axi_trace_awlock,
  output wire [3:0]                   m_axi_trace_awcache,
  output wire [2:0]                   m_axi_trace_awprot,
  output wire [3:0]                   m_axi_trace_awqos,
  output wire                         m_axi_trace_wvalid,
  input  wire                         m_axi_trace_wready,
  output wire [`NPC_FPGA_XLEN-1:0]   m_axi_trace_wdata,
  output wire [`NPC_FPGA_XLEN/8-1:0] m_axi_trace_wstrb,
  output wire                         m_axi_trace_wlast,
  input  wire                         m_axi_trace_bvalid,
  output wire                         m_axi_trace_bready,
  input  wire [3:0]                   m_axi_trace_bid,
  input  wire [1:0]                   m_axi_trace_bresp,
  output wire                         m_axi_trace_arvalid,
  input  wire                         m_axi_trace_arready,
  output wire [63:0]                  m_axi_trace_araddr,
  output wire [3:0]                   m_axi_trace_arid,
  output wire [7:0]                   m_axi_trace_arlen,
  output wire [2:0]                   m_axi_trace_arsize,
  output wire [1:0]                   m_axi_trace_arburst,
  output wire                         m_axi_trace_arlock,
  output wire [3:0]                   m_axi_trace_arcache,
  output wire [2:0]                   m_axi_trace_arprot,
  output wire [3:0]                   m_axi_trace_arqos,
  input  wire                         m_axi_trace_rvalid,
  output wire                         m_axi_trace_rready,
  input  wire [3:0]                   m_axi_trace_rid,
  input  wire [`NPC_FPGA_XLEN-1:0]   m_axi_trace_rdata,
  input  wire [1:0]                   m_axi_trace_rresp,
  input  wire                         m_axi_trace_rlast,
`endif

  input  wire                         s_axi_control_awvalid,
  output wire                         s_axi_control_awready,
  input  wire [11:0]                  s_axi_control_awaddr,
  input  wire                         s_axi_control_wvalid,
  output wire                         s_axi_control_wready,
  input  wire [31:0]                  s_axi_control_wdata,
  input  wire [3:0]                   s_axi_control_wstrb,
  output wire                         s_axi_control_bvalid,
  input  wire                         s_axi_control_bready,
  output wire [1:0]                   s_axi_control_bresp,
  input  wire                         s_axi_control_arvalid,
  output wire                         s_axi_control_arready,
  input  wire [11:0]                  s_axi_control_araddr,
  output wire                         s_axi_control_rvalid,
  input  wire                         s_axi_control_rready,
  output wire [31:0]                  s_axi_control_rdata,
  output wire [1:0]                   s_axi_control_rresp
);
  wire [31:0] core_awaddr;
  wire [31:0] core_araddr;
  wire [63:0] memory_host_base;

  assign m_axi_gmem_awaddr = memory_host_base + {32'b0, core_awaddr - GUEST_MEMORY_BASE};
  assign m_axi_gmem_araddr = memory_host_base + {32'b0, core_araddr - GUEST_MEMORY_BASE};

  NpcFpgaTop core (
    .clock(ap_clk),
    .reset(!ap_rst_n),
    .io_interrupt(1'b0),
    .io_master_aw_ready(m_axi_gmem_awready),
    .io_master_aw_valid(m_axi_gmem_awvalid),
    .io_master_aw_bits_id(m_axi_gmem_awid),
    .io_master_aw_bits_addr(core_awaddr),
    .io_master_aw_bits_len(m_axi_gmem_awlen),
    .io_master_aw_bits_size(m_axi_gmem_awsize),
    .io_master_aw_bits_burst(m_axi_gmem_awburst),
    .io_master_aw_bits_lock(m_axi_gmem_awlock),
    .io_master_aw_bits_cache(m_axi_gmem_awcache),
    .io_master_aw_bits_prot(m_axi_gmem_awprot),
    .io_master_aw_bits_qos(m_axi_gmem_awqos),
    .io_master_w_ready(m_axi_gmem_wready),
    .io_master_w_valid(m_axi_gmem_wvalid),
    .io_master_w_bits_data(m_axi_gmem_wdata),
    .io_master_w_bits_strb(m_axi_gmem_wstrb),
    .io_master_w_bits_last(m_axi_gmem_wlast),
    .io_master_b_ready(m_axi_gmem_bready),
    .io_master_b_valid(m_axi_gmem_bvalid),
    .io_master_b_bits_id(m_axi_gmem_bid),
    .io_master_b_bits_resp(m_axi_gmem_bresp),
    .io_master_ar_ready(m_axi_gmem_arready),
    .io_master_ar_valid(m_axi_gmem_arvalid),
    .io_master_ar_bits_id(m_axi_gmem_arid),
    .io_master_ar_bits_addr(core_araddr),
    .io_master_ar_bits_len(m_axi_gmem_arlen),
    .io_master_ar_bits_size(m_axi_gmem_arsize),
    .io_master_ar_bits_burst(m_axi_gmem_arburst),
    .io_master_ar_bits_lock(m_axi_gmem_arlock),
    .io_master_ar_bits_cache(m_axi_gmem_arcache),
    .io_master_ar_bits_prot(m_axi_gmem_arprot),
    .io_master_ar_bits_qos(m_axi_gmem_arqos),
    .io_master_r_ready(m_axi_gmem_rready),
    .io_master_r_valid(m_axi_gmem_rvalid),
    .io_master_r_bits_id(m_axi_gmem_rid),
    .io_master_r_bits_data(m_axi_gmem_rdata),
    .io_master_r_bits_resp(m_axi_gmem_rresp),
    .io_master_r_bits_last(m_axi_gmem_rlast),
`ifdef NPC_FPGA_RUNTIME_TRACE
    .io_trace_aw_ready(m_axi_trace_awready),
    .io_trace_aw_valid(m_axi_trace_awvalid),
    .io_trace_aw_bits_id(m_axi_trace_awid),
    .io_trace_aw_bits_addr(m_axi_trace_awaddr),
    .io_trace_aw_bits_len(m_axi_trace_awlen),
    .io_trace_aw_bits_size(m_axi_trace_awsize),
    .io_trace_aw_bits_burst(m_axi_trace_awburst),
    .io_trace_aw_bits_lock(m_axi_trace_awlock),
    .io_trace_aw_bits_cache(m_axi_trace_awcache),
    .io_trace_aw_bits_prot(m_axi_trace_awprot),
    .io_trace_aw_bits_qos(m_axi_trace_awqos),
    .io_trace_w_ready(m_axi_trace_wready),
    .io_trace_w_valid(m_axi_trace_wvalid),
    .io_trace_w_bits_data(m_axi_trace_wdata),
    .io_trace_w_bits_strb(m_axi_trace_wstrb),
    .io_trace_w_bits_last(m_axi_trace_wlast),
    .io_trace_b_ready(m_axi_trace_bready),
    .io_trace_b_valid(m_axi_trace_bvalid),
    .io_trace_b_bits_id(m_axi_trace_bid),
    .io_trace_b_bits_resp(m_axi_trace_bresp),
    .io_trace_ar_ready(m_axi_trace_arready),
    .io_trace_ar_valid(m_axi_trace_arvalid),
    .io_trace_ar_bits_id(m_axi_trace_arid),
    .io_trace_ar_bits_addr(m_axi_trace_araddr),
    .io_trace_ar_bits_len(m_axi_trace_arlen),
    .io_trace_ar_bits_size(m_axi_trace_arsize),
    .io_trace_ar_bits_burst(m_axi_trace_arburst),
    .io_trace_ar_bits_lock(m_axi_trace_arlock),
    .io_trace_ar_bits_cache(m_axi_trace_arcache),
    .io_trace_ar_bits_prot(m_axi_trace_arprot),
    .io_trace_ar_bits_qos(m_axi_trace_arqos),
    .io_trace_r_ready(m_axi_trace_rready),
    .io_trace_r_valid(m_axi_trace_rvalid),
    .io_trace_r_bits_id(m_axi_trace_rid),
    .io_trace_r_bits_data(m_axi_trace_rdata),
    .io_trace_r_bits_resp(m_axi_trace_rresp),
    .io_trace_r_bits_last(m_axi_trace_rlast),
`endif
    .io_control_aw_ready(s_axi_control_awready),
    .io_control_aw_valid(s_axi_control_awvalid),
    .io_control_aw_bits_addr({20'b0, s_axi_control_awaddr}),
    .io_control_aw_bits_size(3'd2),
    .io_control_aw_bits_prot(3'd0),
    .io_control_w_ready(s_axi_control_wready),
    .io_control_w_valid(s_axi_control_wvalid),
    .io_control_w_bits_data(s_axi_control_wdata),
    .io_control_w_bits_strb(s_axi_control_wstrb),
    .io_control_b_ready(s_axi_control_bready),
    .io_control_b_valid(s_axi_control_bvalid),
    .io_control_b_bits_resp(s_axi_control_bresp),
    .io_control_ar_ready(s_axi_control_arready),
    .io_control_ar_valid(s_axi_control_arvalid),
    .io_control_ar_bits_addr({20'b0, s_axi_control_araddr}),
    .io_control_ar_bits_size(3'd2),
    .io_control_ar_bits_prot(3'd0),
    .io_control_r_ready(s_axi_control_rready),
    .io_control_r_valid(s_axi_control_rvalid),
    .io_control_r_bits_data(s_axi_control_rdata),
    .io_control_r_bits_resp(s_axi_control_rresp),
    .io_mailboxInterrupt(interrupt),
    .io_memoryHostBase(memory_host_base)
  );
endmodule
