#ifndef NEMU_FPGA_MAILBOX_H
#define NEMU_FPGA_MAILBOX_H

#include <stddef.h>
#include <stdint.h>

#include <npc-fpga-trace.h>

enum nemu_fpga_runtime_register {
  NEMU_FPGA_DEBUG_CAPABILITIES = 0x3c,
  NEMU_FPGA_DEBUG_COMMAND_SEQUENCE = 0x40,
  NEMU_FPGA_DEBUG_COMMAND = 0x44,
  NEMU_FPGA_DEBUG_COMPLETED_SEQUENCE = 0x48,
  NEMU_FPGA_DEBUG_STATUS = 0x4c,
  NEMU_FPGA_DEBUG_STOP_PC_LOW = 0x50,
  NEMU_FPGA_DEBUG_STOP_PC_HIGH = 0x54,
  NEMU_FPGA_DEBUG_STOP_REASON = 0x58,
  NEMU_FPGA_DEBUG_CSR_INDEX = 0x5c,
  NEMU_FPGA_RT_COMPLETION_PC_LOW = 0x60,
  NEMU_FPGA_RT_COMPLETION_PC_HIGH = 0x64,
  NEMU_FPGA_RT_COMPLETION_NEXT_PC_LOW = 0x68,
  NEMU_FPGA_RT_COMPLETION_NEXT_PC_HIGH = 0x6c,
  NEMU_FPGA_RT_GUEST_INTERRUPT = 0x70,
  NEMU_FPGA_RT_CONTROL = 0x80,
  NEMU_FPGA_RT_STATUS = 0x84,
  NEMU_FPGA_RT_INFO = 0x88,
  NEMU_FPGA_RT_REGISTER_INDEX = 0x8c,
  NEMU_FPGA_RT_GPR_LOW = 0x90,
  NEMU_FPGA_RT_GPR_HIGH = 0x94,
  NEMU_FPGA_RT_FPR_LOW = 0x98,
  NEMU_FPGA_RT_FPR_HIGH = 0x9c,
  NEMU_FPGA_RT_FCSR = 0xa0,
  NEMU_FPGA_RT_MSTATUS_LOW = 0xa4,
  NEMU_FPGA_RT_MSTATUS_HIGH = 0xa8,
  NEMU_FPGA_RT_CURRENT_PC_LOW = 0xac,
  NEMU_FPGA_RT_CURRENT_PC_HIGH = 0xb0,
  NEMU_FPGA_RT_COMMIT_PC_LOW = 0xb4,
  NEMU_FPGA_RT_COMMIT_PC_HIGH = 0xb8,
  NEMU_FPGA_RT_COMMIT_INSTRUCTION = 0xbc,
  NEMU_FPGA_RT_COMMIT_NEXT_PC_LOW = 0xc0,
  NEMU_FPGA_RT_COMMIT_NEXT_PC_HIGH = 0xc4,
  NEMU_FPGA_RT_CYCLE_LOW = 0xc8,
  NEMU_FPGA_RT_CYCLE_HIGH = 0xcc,
  NEMU_FPGA_RT_COMMIT_COUNT_LOW = 0xd0,
  NEMU_FPGA_RT_COMMIT_COUNT_HIGH = 0xd4,
  NEMU_FPGA_RT_COMPLETION_CODE_LOW = 0xd8,
  NEMU_FPGA_RT_COMPLETION_CODE_HIGH = 0xdc,
  NEMU_FPGA_RT_BACKPRESSURE = 0xe0,
  NEMU_FPGA_RT_FRONTEND_INSTRUCTION = 0xe4,
  NEMU_FPGA_RT_PUTCH_DATA = 0xe8,
  NEMU_FPGA_DEBUG_CSR_LOW = 0xec,
  NEMU_FPGA_RT_MEMORY_HOST_BASE_LOW = 0xf0,
  NEMU_FPGA_RT_MEMORY_HOST_BASE_HIGH = 0xf4,
  NEMU_FPGA_DEBUG_CSR_HIGH = 0xf8,
  NEMU_FPGA_DEBUG_PROTOCOL = 0xfc,
  NEMU_FPGA_TRACE_CAPABILITY = 0x100,
  NEMU_FPGA_TRACE_FORMAT = 0x104,
  NEMU_FPGA_TRACE_RECORD_BYTES = 0x108,
  NEMU_FPGA_TRACE_MAX_RECORDS = 0x10c,
  NEMU_FPGA_TRACE_RECORDS_LOW = 0x110,
  NEMU_FPGA_TRACE_RECORDS_HIGH = 0x114,
  NEMU_FPGA_TRACE_DROPPED_LOW = 0x118,
  NEMU_FPGA_TRACE_DROPPED_HIGH = 0x11c,
  NEMU_FPGA_TRACE_HOST_BASE_LOW = 0x120,
  NEMU_FPGA_TRACE_HOST_BASE_HIGH = 0x124,
  NEMU_FPGA_TRACE_CLASS_SELECTOR = 0x128,
  NEMU_FPGA_TRACE_STAGE_SELECTOR = 0x12c,
  NEMU_FPGA_TRACE_CLASS_COUNT_LOW = 0x130,
  NEMU_FPGA_TRACE_CLASS_COUNT_HIGH = 0x134,
  NEMU_FPGA_TRACE_STAGE_TOTAL_LOW = 0x138,
  NEMU_FPGA_TRACE_STAGE_TOTAL_HIGH = 0x13c,
  NEMU_FPGA_TRACE_CLASS_MAX_LOW = 0x140,
  NEMU_FPGA_TRACE_CLASS_MAX_HIGH = 0x144,
  NEMU_FPGA_TRACE_CLASS_LAST_PC_LOW = 0x148,
  NEMU_FPGA_TRACE_CLASS_LAST_PC_HIGH = 0x14c,
  NEMU_FPGA_TRACE_CLASS_LAST_INSTRUCTION = 0x150,
  NEMU_FPGA_TRACE_CLASS_LAST_STAGE_LOW = 0x154,
  NEMU_FPGA_TRACE_CLASS_LAST_STAGE_HIGH = 0x158,
  NEMU_FPGA_TRACE_LAST_CLASS = 0x15c,
  NEMU_FPGA_TRACE_STALL_SELECTOR = 0x160,
  NEMU_FPGA_TRACE_STALL_LOW = 0x164,
  NEMU_FPGA_TRACE_STALL_HIGH = 0x168,
  NEMU_FPGA_TRACE_CYCLES_LOW = 0x16c,
  NEMU_FPGA_TRACE_CYCLES_HIGH = 0x170,
  NEMU_FPGA_TRACE_COMMITS_LOW = 0x174,
  NEMU_FPGA_TRACE_COMMITS_HIGH = 0x178,
  NEMU_FPGA_TRACE_PIPELINE_FEATURES = 0x17c,
  NEMU_FPGA_TRACE_FLAGS = 0x180,
  NEMU_FPGA_TRACE_LAST_TOTAL_LOW = 0x184,
  NEMU_FPGA_TRACE_LAST_TOTAL_HIGH = 0x188,
};

enum nemu_fpga_runtime_control_bits {
  NEMU_FPGA_RT_CORE_RESET = 1u << 0,
  NEMU_FPGA_RT_START = 1u << 1,
  NEMU_FPGA_RT_CLEAR_HALT = NEMU_FPGA_RT_START,
  NEMU_FPGA_RT_ACK_PUTCH = 1u << 2,
  NEMU_FPGA_RT_ACK_COMPLETION = 1u << 3,
};

enum nemu_fpga_guest_interrupt_bits {
  NEMU_FPGA_RT_GUEST_INTERRUPT_MEIP = 1u << 0,
};

enum nemu_fpga_runtime_status_bits {
  NEMU_FPGA_RT_RUNNING = 1u << 0,
  NEMU_FPGA_RT_HALTED = 1u << 1,
  NEMU_FPGA_RT_PUTCH_PENDING = 1u << 2,
  NEMU_FPGA_RT_PROTOCOL_ERROR = 1u << 3,
  NEMU_FPGA_RT_COMPLETION_PENDING = 1u << 4,
};

#define NEMU_FPGA_DEBUG_PROTOCOL_V6 UINT32_C(0x4e504306)
#define NEMU_FPGA_TRACE_FORMAT_V1 1u
#define NEMU_FPGA_TRACE_RECORD_BYTES_V1 NPC_FPGA_TRACE_RECORD_BYTES_V1
#define NEMU_FPGA_TRACE_MAX_RECORDS_V1 200000u
#define NEMU_FPGA_TRACE_BUFFER_BYTES_V1 (16u * 1024u * 1024u)

enum nemu_fpga_trace_flag_bits {
  NEMU_FPGA_TRACE_ENABLED = 1u << 0,
  NEMU_FPGA_TRACE_DRAINED = 1u << 1,
};

enum nemu_fpga_debug_capability_bits {
  NEMU_FPGA_DEBUG_CAP_HALT_STEP = 1u << 0,
  NEMU_FPGA_DEBUG_CAP_TARGET_MEMORY = 1u << 1,
  NEMU_FPGA_DEBUG_CAP_CSR_SNAPSHOT = 1u << 2,
};

enum nemu_fpga_debug_command {
  NEMU_FPGA_DEBUG_HALT = 1,
  NEMU_FPGA_DEBUG_RESUME = 2,
  NEMU_FPGA_DEBUG_STEP = 3,
};

enum nemu_fpga_debug_status_bits {
  NEMU_FPGA_DEBUG_RUNNING = 1u << 0,
  NEMU_FPGA_DEBUG_HALTED = 1u << 1,
  NEMU_FPGA_DEBUG_HALTING = 1u << 2,
  NEMU_FPGA_DEBUG_STEPPING = 1u << 3,
  NEMU_FPGA_DEBUG_IN_RESET = 1u << 4,
  NEMU_FPGA_DEBUG_ERROR = 1u << 5,
};

enum nemu_fpga_debug_stop_reason {
  NEMU_FPGA_STOP_NONE = 0,
  NEMU_FPGA_STOP_HALT_REQUEST = 1,
  NEMU_FPGA_STOP_STEP = 2,
  NEMU_FPGA_STOP_EBREAK = 3,
};

enum nemu_fpga_debug_csr {
  NEMU_FPGA_CSR_MSTATUS = 0,
  NEMU_FPGA_CSR_MCAUSE = 1,
  NEMU_FPGA_CSR_MEPC = 2,
  NEMU_FPGA_CSR_MTVEC = 3,
  NEMU_FPGA_CSR_FCSR = 4,
  NEMU_FPGA_CSR_PC = 5,
};

struct nemu_fpga_mailbox_io {
  void *opaque;
  uint32_t (*read32)(void *opaque, uint32_t offset);
  void (*write32)(void *opaque, uint32_t offset, uint32_t value);
};

enum nemu_fpga_runtime_event_type {
  NEMU_FPGA_RT_EVENT_NONE = 0,
  NEMU_FPGA_RT_EVENT_PUTCH,
  NEMU_FPGA_RT_EVENT_COMPLETION,
  NEMU_FPGA_RT_EVENT_ERROR,
};

struct nemu_fpga_runtime_event {
  enum nemu_fpga_runtime_event_type type;
  uint64_t value;
  int error;
};

int nemu_fpga_runtime_hold_reset(const struct nemu_fpga_mailbox_io *io);
int nemu_fpga_runtime_start(const struct nemu_fpga_mailbox_io *io);
int nemu_fpga_runtime_start_halted(const struct nemu_fpga_mailbox_io *io);
struct nemu_fpga_runtime_event
nemu_fpga_runtime_service_once(const struct nemu_fpga_mailbox_io *io);
uint64_t nemu_fpga_runtime_read_counter(const struct nemu_fpga_mailbox_io *io,
                                        uint32_t low_offset, uint32_t high_offset);

#endif
