include $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../common/config.mk)

FPGA_CONFIG_FORMAT := 4
FPGA_NAME := zcu102
# 器件、平台与工具链均来自终端 FpgaToolchainConfig；本文件只保留独立的板卡
# 硬件约束和 Tcl/IP 目录策略。
FPGA_ALLOWED_CLOCK_MHZ := 300

FPGA_DEFAULT_SOC := ysyx
FPGA_DEFAULT_XLEN := 32
FPGA_M := 1
FPGA_F := 1

FPGA_MEMORY_BASE := 0x80000000
FPGA_MEMORY_HOST_BASE := 0x70000000
FPGA_MEMORY_SIZE := 0x08000000
FPGA_CONTROL_BASE := 0xa0000000
FPGA_MAILBOX_BASE := 0xa0010000
FPGA_MUL_CYCLES := 3
FPGA_MUL_II := 1
FPGA_DIV_CYCLES := 37
FPGA_DIV_II := 1
FPGA_DIV_IP_CYCLES := 34
FPGA_DIV_ADAPTER_CYCLES := 3
FPGA_FADD_CYCLES := 3
FPGA_FADD_II := 1
FPGA_FMUL_CYCLES := 4
FPGA_FMUL_II := 1
FPGA_FDIV_CYCLES := 29
FPGA_FDIV_II := 1
FPGA_FMA_CYCLES := 4
FPGA_FMA_II := 1
FPGA_FSQRT_CYCLES := 29
FPGA_FSQRT_II := 1
FPGA_FCVT_CYCLES := 7
FPGA_FCVT_II := 1
FPGA_FCMP_CYCLES := 3
FPGA_FCMP_II := 1
