package npc

import chisel3._
import chisel3.simulator.EphemeralSimulator._
import org.scalatest.flatspec.AnyFlatSpec

class BranchPredictorBehaviorTest extends AnyFlatSpec {
  "BranchPredictor" should "keep static direction before training and learn resolved outcomes" in {
    simulate(new BranchPredictor(addrWidth = 32, entries = 8, returnEntries = 8)) { dut =>
      dut.io.queryValid.poke(false)
      dut.io.queryPc.poke(0)
      dut.io.queryConditional.poke(false)
      dut.io.queryJalr.poke(false)
      dut.io.queryReturn.poke(false)
      dut.io.queryStaticTaken.poke(false)
      dut.io.resolveValid.poke(false)
      dut.io.resolvePc.poke(0)
      dut.io.resolveConditional.poke(false)
      dut.io.resolveJalr.poke(false)
      dut.io.resolveCall.poke(false)
      dut.io.resolveReturn.poke(false)
      dut.io.resolveTaken.poke(false)
      dut.io.resolveTarget.poke(0)
      dut.reset.poke(true)
      dut.clock.step(2)
      dut.reset.poke(false)

      dut.io.queryValid.poke(true)
      dut.io.queryPc.poke(0x20)
      dut.io.queryConditional.poke(true)
      dut.io.queryStaticTaken.poke(false)
      dut.io.predictTaken.expect(false.B)
      dut.io.queryStaticTaken.poke(true)
      dut.io.predictTaken.expect(true.B)

      dut.io.resolveValid.poke(true)
      dut.io.resolvePc.poke(0x20)
      dut.io.resolveConditional.poke(true)
      dut.io.resolveTaken.poke(true)
      dut.clock.step()
      dut.io.resolveValid.poke(false)
      dut.io.resolveConditional.poke(false)
      dut.io.queryStaticTaken.poke(false)
      dut.io.predictTaken.expect(true.B)

      dut.io.resolveValid.poke(true)
      dut.io.resolveConditional.poke(true)
      dut.io.resolveTaken.poke(false)
      dut.clock.step()
      dut.io.resolveValid.poke(false)
      dut.io.resolveConditional.poke(false)
      dut.clock.step()
      dut.io.resolveValid.poke(true)
      dut.io.resolveConditional.poke(true)
      dut.io.resolveTaken.poke(false)
      dut.clock.step()
      dut.io.resolveValid.poke(false)
      dut.io.predictTaken.expect(false.B)

      dut.io.queryConditional.poke(false)
      dut.io.queryJalr.poke(true)
      dut.io.queryReturn.poke(false)
      dut.io.queryPc.poke(0x48)
      dut.io.predictJalrValid.expect(false.B)
      dut.io.resolveValid.poke(true)
      dut.io.resolvePc.poke(0x48)
      dut.io.resolveJalr.poke(true)
      dut.io.resolveTarget.poke(0x180)
      dut.clock.step()
      dut.io.resolveValid.poke(false)
      dut.io.resolveJalr.poke(false)
      dut.io.predictJalrValid.expect(true.B)
      dut.io.predictJalrTarget.expect(0x180.U)

      dut.io.queryJalr.poke(false)
      dut.io.queryReturn.poke(true)
      dut.io.queryPc.poke(0x88)
      dut.io.predictReturnValid.expect(false.B)
      dut.io.resolveValid.poke(true)
      dut.io.resolvePc.poke(0x80)
      dut.io.resolveCall.poke(true)
      dut.clock.step()
      dut.io.resolveValid.poke(false)
      dut.io.resolveCall.poke(false)
      dut.io.predictReturnValid.expect(true.B)
      dut.io.predictReturnTarget.expect(0x84.U)
      dut.io.resolveValid.poke(true)
      dut.io.resolveReturn.poke(true)
      dut.clock.step()
      dut.io.resolveValid.poke(false)
      dut.io.resolveReturn.poke(false)
      dut.io.predictReturnValid.expect(false.B)
    }
  }
}
